name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: paulodalves/cobalt
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/imputnet/cobalt.git
          git fetch upstream

      - name: Merge upstream changes
        id: merge
        run: |
          git checkout main
          git merge upstream/main --ff-only && echo "::set-output name=updated::true" || { echo "::set-output name=updated::false"; }

      - name: Push merged changes
        if: steps.merge.outputs.updated == 'true'
        run: |
          git push origin main

      - name: Notify Telegram on Update
        if: steps.merge.outputs.updated == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            ✅ Repositório atualizado com sucesso!
            Upstream: imputnet/cobalt
            Fork: ${{ github.repository }}
            Commit: ${{ github.sha }}
